### ISSUE TITLE
Media buttons bugs

### ISSUE THREAD

**Issue by st1ng7ay** [SokoloffA/radiola#18]
1. Play/pause button at keyboard work with other objects ( radiola not locked media keys to it's audio stream. F.e. i have youtube tab and radiola - play/pause work at same time at all of them ).
2. Previous / forward buttons not change favorite stations ( i set this option at menu )
<img width="596" alt="image" src="https://github.com/SokoloffA/radiola/assets/79450231/d0142b21-183c-49e0-8bf7-f6b2d5d76a7e">

**Comment by SokoloffA** [comment]
1. I do not know if it is possible to exclusively capture multimedia keys. I'll do some additional research. If you know a program that does this, with open source, I will be grateful.
2. I will release a special debugging version and we will find the problem.

**Comment by st1ng7ay** [comment]
1. [Custer](https://github.com/exelban/custer)

**Comment by SokoloffA** [comment]
Thanks! I'll see how it's done in the Custer.

**Comment by heliocastro** [comment]
Maybe i can add an entry in this bug, since is related to media buttons as well. Please correct me is this is the wrong place.
Since Radiola is not registered to main system, media buttons works properly, but then activate other registered player when used.

Quick examples:
- Radiola is playing
- Play/Pause media button is pressed
- Radiola stops but MacOS  player starts

- Radiola stream stopped, but started on startup
- Play button is pressed
- Both Mac player and Radiola starts

**Comment by SokoloffA** [comment]
I've [released a beta version](https://github.com/SokoloffA/radiola/releases/tag/v5.99.1) of the software with fulfil your dreams. 
I'm interested to hear your opinion.

**Comment by st1ng7ay** [comment]
Thank you.
all is awesome!

**Comment by heliocastro** [comment]
Yes, is really great. Big thanks

Btw, just FIY i'm a fan of one amazing free internet radio for years, http://somafm.com, and i did this small importer to Radiola:
https://github.com/heliocastro/somafm-import

Is a simple tool, just to keep the channels updated if you are curious.
