### ISSUE TITLE
Feature request: buffer for not stable network urls

### ISSUE THREAD

**Issue by st1ng7ay** [SokoloffA/radiola#19]
with radiola i have sometimes disconnections for 1-2 second.
i test another app,  it have 30 second buffer - and no disconnections at all

**Comment by SokoloffA** [comment]
Hi!

I specifically [set the buffer to 1 second](https://github.com/SokoloffA/radiola/blob/bbdffa77fd814ac7fe4c4d1cb81d0ddacc898146/Radiola/Player.swift#L126). Increasing this buffer adds a delay after clicking on the play button, because the player is silent until it downloads N seconds to the buffer. 

1. I'll try to play with the buffer size.
2. What is the name of the another app with a 30-second buffer? Are the source codes available? Does it have a delay at the beginning of playback?

**Comment by st1ng7ay** [comment]
It's [Custer](https://github.com/exelban/custer)
no delay at startup - buffer increases after playing starts.

**Comment by SokoloffA** [comment]
Thanks! I'll see how it's done in the Custer.
