### ISSUE TITLE
Menu icon behavior

### ISSUE THREAD

**Issue by st1ng7ay** [SokoloffA/radiola#21]
Hi.
As for me, playing states at menu icon are inverted:

- playing (expected icon is pause "||" )
- paused (expected icon is play "|>")

**Comment by SokoloffA** [comment]
It is always a difficult question whether to show the icon of the current **state** or the icon of the **command** that will be executed.

I decided to show **command** icon . Because:
1. It matches the icon on the main window. Last coincides with icons in other programmes, e.g. iTunes
2. It matches the icon in the Plaing Now panel. 

 ![Plaing Now](https://discussions.apple.com/content/attachment/92715608-c7ca-4823-be37-7821098084be)

**Comment by st1ng7ay** [comment]
I have different states (music is playing) : 
![image](https://github.com/SokoloffA/radiola/assets/79450231/f91cb101-4517-42d7-bd37-7da5ee99e9fc)

**Comment by fulldecent** [comment]
This is currently working for me in version Version 6.1.0

**Comment by SokoloffA** [comment]
@fulldecent 
> This is currently working for me in version Version 6.1.0

Please clarify what you mean. 
* The play button enables/disables playback.
* You like the icons.
* You agree with st1ng7ay and think icons should be changed.


@st1ng7ay 
> I have different states (music is playing) :

In my opinion the meaning of these icons is different, one is a button, the other is an indicator. 
I realize that if icons are placed next to each other it looks strange, but unfortunately there is no perfect solution.  
Most of the time people only see the tray icon. And if a pause is drawn on it when playback starts, it will be more confusing.

So for now, the icons will remain as they are.
