### ISSUE TITLE
Minimum OS requirement

### ISSUE THREAD

**Issue by sosh72** [SokoloffA/radiola#47]
App won't start and says MacOS 11 or higher required.
I'm still on Catalina and won't upgrade for good reasons.

Is there any good reason for this requirement, or is this just a by-product of the toolchain you use?

**Comment by SokoloffA** [comment]
Unfortunately, when Apple adds new features, they don't port them to older systems. 
I did encounter compilation errors of the form *"SOME_FUNC is only available in macOS 11.0 or newer"*.
I don't remember all of them, here are a few:
* 'init(systemSymbolName:accessibilityDescription:)' is only available in macOS 11.0 or newer
* 'constraint(equalToSystemSpacingAfter:multiplier:)' is only available in macOS 11.0 or newer
If my memory serves me right, there were more.

I'm trying to make it work in all supported versions of mac OS (now from Ventura). Plus unsupported versions if it doesn't cause big problems. Unfortunately, a lot of features have been added and fixed in Big Sur.
