### ISSUE TITLE
Support Homebrew ?

### ISSUE THREAD

**Issue by dylandea** [SokoloffA/radiola#5]
Hi
I'd like to see this app on homebrew if it's something you are intending to do.

That's a very cool app, responding to all my needs, thanks for this masterpiece mate !

**Comment by SokoloffA** [comment]
Hi!
I was thinking about homebrew, but I'm afraid my app doesn't meet the following condition from their [Acceptable Formulae](https://docs.brew.sh/Acceptable-Formulae#niche-or-self-submitted-stuff).

> **Niche (or self-submitted) stuff**
> The software in question must:
>* be known
>
> We frown on authors submitting their own work unless it is very popular.

**Comment by toobuntu** [comment]
Thank you for such great software! It's tiny, lightweight, and yet does exactly what we were looking for.

Would you consider hosting your own [Homebrew tap](https://docs.brew.sh/How-to-Create-and-Maintain-a-Tap)?

If you do, you could add to a GitHub workflow to run `brew bump-cask-pr` on each release to keep the tap up to date.

I've done a prototype cask for Radiola, shown below. In doing so, there was one question I had. In `Radiola.xcodeproj/project.pbxproj`, there are two macOS deployment targets:
 `MACOSX_DEPLOYMENT_TARGET = 10.15;` (Catalina) and 
 `MACOSX_DEPLOYMENT_TARGET = 11.0;` (Big Sur). [Macupdater](https://macupdater.net/app_updates/appinfo/com.github.SokoloffA.Radiola/index.html) reports the minimum OS for Radiola as macOS 11.0, so I went with `depends_on macos: ">= :big_sur"`. Was that correct?

Here's the cask:
```
cask "radiola" do
  version "5.1.1"
  sha256 "95a74d5afcb655722bb64ed65ae5f6eebb040a7e3a583eecdfc326741d3ff7a1"

  url "https://github.com/SokoloffA/radiola/releases/download/v#{version}/Radiola-#{version}.dmg",
  name "Radiola"
  desc "Lightweight Internet radio player for the macOS status bar"
  homepage "https://github.com/SokoloffA/radiola"

  # If you're not planning on pre-releases the whole livecheck block can be removed,
  # as Homebrew will default to using the :git strategy (inferred from the url) which
  # doesn't rely upon the GitHub API.
  # -> But Radiola has issued betas with pre-release tags in GitHub.
  livecheck do
    url :url
    strategy :github_releases
  end
  
  depends_on macos: ">= :big_sur"
  
  app "Radiola.app"

  uninstall quit: "com.github.SokoloffA.Radiola"

  zap trash: [
    "~/Library/Application Support/com.github.SokoloffA.Radiola/bookmarks.opml",
    "~/Library/Caches/com.github.SokoloffA.Radiola",
    "~/Library/HTTPStorages/com.github.SokoloffA.Radiola",
    "~/Library/Preferences/com.github.SokoloffA.Radiola.plist",
  ]
end
```

Thank you for your consideration.

**Comment by SokoloffA** [comment]
Nothing ventured, nothing gained!
I'll try to suggest to the official repository. If they don't accept it, I'll make my own tap.

**Comment by SokoloffA** [comment]
Didn't they switch to JSON?

**Comment by toobuntu** [comment]
> Didn't they switch to JSON?

Short answer: No, a formula or cask is still a block of Ruby code. See https://docs.brew.sh/Cask-Cookbook.

Long answer: As of 4.0.0, Homebrew uses JSON files downloaded from [formulae.brew.sh](https://formulae.brew.sh/) for package installation rather than local homebrew/core and homebrew/cask taps. This enables significantly faster Homebrew-maintained tap updates by migrating from Git-cloned taps to JSON downloads. Users can query the JSON API using the `brew info` command.

Unfortunately, I think Radiola will not be accepted into Homebrew yet because it fails to pass the notability threshold (under 30 forks, 30 watchers, 75 stars) or justify an exception. See https://docs.brew.sh/Acceptable-Casks#exceptions-to-the-notability-threshold and https://docs.brew.sh/Adding-Software-to-Homebrew#casks and the output of  `brew audit --new-cask radiola`.
```
...

Error: 2 problems in 1 cask detected.
  audit for radiola: failed
   - GitHub repository not notable enough (<30 forks, <30 watchers and <75 stars)
   - Signature verification failed:
  /private/tmp/d20230805-63092-1unnxel/Radiola.app: rejected

  macOS on ARM requires software to be signed.
  Please contact the upstream developer to let them know they should sign and notarize their software.
...
```

Below is an updated cask prototype for Radiola v5.2.0.

Note that with the release of 5.2.0, the livecheck stanza had to be updated. See https://docs.brew.sh/Brew-Livecheck for more information about that stanza. It needs github_releases to deal with the pre-release tags and now also a more sophisticated json parser to match the version string. This is because the release tag is v5.2 and the version is 5.2.0. I also ran `brew createzap` and updated the zap stanza accordingly.

Here’s the updated cask:
`cat "$(brew --repository homebrew/cask)/Casks/radiola.rb"`
```
cask "radiola" do
  version "5.2.0"
  sha256 "ebe4ee66abdbd73b4208f04399c7bcec552412ab38364fb5daed0744057e35d8"

  url "https://github.com/SokoloffA/radiola/releases/download/v#{version.major_minor}/Radiola-#{version}.dmg"
  name "Radiola"
  desc "Lightweight Internet radio player for the menu bar"
  homepage "https://github.com/SokoloffA/radiola"

  # If you're not planning on pre-releases the whole livecheck block can be removed,
  # as Homebrew will default to using the :git strategy (inferred from the url) which
  # doesn't rely upon the GitHub API.
  # -> But Radiola has issued betas with pre-release tags in GitHub.
  # -> Also, the release tag can be v5.2 and the version 5.2.0.
  livecheck do
    url :homepage
    regex(/Radiola[._-]v?(\d+(?:\.\d+)+)\.dmg/i)
    strategy :github_releases do |json, regex|
      json.map do |release|
        curr_asset = release["assets"]&.find { |asset| asset["browser_download_url"]&.match(regex) }
        next if curr_asset.blank?

        curr_asset["browser_download_url"][regex, 1]
      end
    end
  end

  depends_on macos: ">= :big_sur"

  app "Radiola.app"

  uninstall quit: "com.github.SokoloffA.Radiola"

  zap trash: [
    "~/Library/Application Support/com.github.SokoloffA.Radiola",
    "~/Library/Caches/com.github.SokoloffA.Radiola",
    "~/Library/HTTPStorages/com.github.SokoloffA.Radiola",
    "~/Library/Preferences/com.github.SokoloffA.Radiola.plist",
    "~/Library/WebKit/com.github.SokoloffA.Radiola",
  ]
end
```

**Comment by SokoloffA** [comment]
> Note that with the release of 5.2.0, the livecheck stanza had to be updated.

That's my fault. I forgot that the release name is included in the URL. In the future I will "zero" releases will be named as M.N.0.

> I went with depends_on macos: ">= :big_sur". Was that correct?

Yes, the minimum version is 11.0. In general, I program in C++ and Qt on Linux, and Xcode project are not clean for me.

**Comment by SokoloffA** [comment]
I've created a repository for [homebrew Tap](https://github.com/SokoloffA/homebrew-radiola).
